"""tablas iniciales

Revision ID: 44010654aca9
Revises: 
Create Date: 2026-01-14 10:32:40.446333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44010654aca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('total_entrepanos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('entrepanos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=1), nullable=False),
    sa.Column('estante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estante_id'], ['estantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('entrepano_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrepano_id'], ['entrepanos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripción', sa.String(length=250), nullable=True),
    sa.Column('maximo', sa.Integer(), nullable=True),
    sa.Column('minimo', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('divisiones')
    op.drop_table('entrepanos')
    op.drop_table('estantes')
    # ### end Alembic commands ###
