"""Agregar identificador a estantes

Revision ID: 8ec939b1cd2a
Revises: 44010654aca9
Create Date: 2026-01-20 09:33:31.156873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec939b1cd2a'
down_revision = '44010654aca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estantes')
    with op.batch_alter_table('estante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_estante', sa.String(length=1), server_default='P', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estante', schema=None) as batch_op:
        batch_op.drop_column('tipo_estante')

    op.create_table('estantes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('numero', sa.INTEGER(), nullable=False),
    sa.Column('total_entrepanos', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###
